name: Build

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    uses: qapital/github-workflows/.github/workflows/build.yml@master
    secrets:
      ACTION_GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
